# Generated by Django 5.2.6 on 2025-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/', verbose_name='PDF Файл'),
        ),
    ]
