# Generated by Django 5.2.6 on 2025-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0002_project_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
